"""Accessibility-tree perception: CDP AX nodes -> RawElements (PLAN.md 4.3, R-SENS-1).

Pure functions - no browser - so they are unit-tested against recorded Chromium
trees (tests/fixtures/ax/, regenerated by scripts/capture_ax_fixtures.py).

What the A3 spike and the recorded trees established, and this module encodes:

* The tree is fetched per frame; the caller passes one node list per frame.
* Chromium repeats text: a cell named "12345" has a StaticText child "12345", and
  the link "View" sits alone in a cell also named "View". Duplicates are dropped so
  each fact reaches the model once.
* A container cell is named after its entire contents ("Joined 2001-07-22 ..."), so
  only leaf cells are kept; a container's children carry its content.
* Whether a table holds data is decided by header cells, not role: the header-less
  tab strip arrives as role=cell.
* Labels come from column and row headers in data tables, and from the cell to the
  left in layout tables - the only link between "Member ID" and its textbox.
"""

from __future__ import annotations

from collections.abc import Iterator, Mapping, Sequence
from dataclasses import dataclass
from typing import Any

from waypoint.surface.ports import RawElement, RawText
from waypoint.surface.sensitivity import (
    VALUE_ROLES,
    Classification,
    ElementFacts,
    SensitivityClassifier,
)

AXNode = dict[str, Any]

INTERACTIVE_ROLES = frozenset(
    {
        "link",
        "button",
        "textbox",
        "searchbox",
        "combobox",
        "listbox",
        "option",
        "checkbox",
        "radio",
        "switch",
        "tab",
        "menuitem",
        "menuitemcheckbox",
        "menuitemradio",
        "spinbutton",
        "slider",
    }
)
CELL_ROLES = frozenset({"cell", "gridcell", "columnheader", "rowheader", "LayoutTableCell"})
HEADER_ROLES = frozenset({"columnheader", "rowheader"})
ROW_ROLES = frozenset({"row", "LayoutTableRow"})
TABLE_ROLES = frozenset({"table", "grid", "treegrid", "LayoutTable"})
NAMED_BLOCK_ROLES = frozenset({"heading", "dialog", "alertdialog", "alert", "status", "image"})
STRUCTURAL_ROLES = INTERACTIVE_ROLES | CELL_ROLES | ROW_ROLES | TABLE_ROLES
MAX_ANCHORS = 6


@dataclass(frozen=True)
class FrameAX:
    """One frame's ``Accessibility.getFullAXTree`` result and where it sits."""

    frame_id: str
    path: tuple[str, ...]
    nodes: Sequence[AXNode]


@dataclass(frozen=True)
class Perceived:
    """A RawElement plus the handles the web surface needs to stamp and act on it."""

    element: RawElement
    frame_id: str
    backend_id: int


def role(n: AXNode) -> str:
    return str((n.get("role") or {}).get("value", ""))


def text(n: AXNode) -> str:
    """Accessible name, with non-breaking spaces normalised and edges trimmed."""
    return str((n.get("name") or {}).get("value", "")).replace("\xa0", " ").strip()


def _prop(n: AXNode, key: str) -> Any:
    for p in n.get("properties", []):
        if p.get("name") == key:
            return (p.get("value") or {}).get("value")
    return None


class _FrameView:
    def __init__(
        self,
        frame: FrameAX,
        classifier: SensitivityClassifier,
        form_attrs: Mapping[str, Mapping[str, str]],
    ) -> None:
        self.frame = frame
        self.classifier = classifier
        self.form_attrs = form_attrs
        self.by_id: dict[str, AXNode] = {n["nodeId"]: n for n in frame.nodes}
        self.headered: set[str] = set()
        for n in frame.nodes:
            if role(n) in HEADER_ROLES and (t := self.ancestor(n, TABLE_ROLES)) is not None:
                self.headered.add(t["nodeId"])
        self._facts: dict[str, ElementFacts] = {}
        self._cls: dict[str, Classification] = {}

    # ----------------------------------------------------------- navigation

    def walk(self) -> Iterator[AXNode]:
        """Every non-ignored node, pre-order, descending through ignored ones."""
        roots = [n for n in self.frame.nodes if "parentId" not in n]
        stack = list(reversed(roots))
        while stack:
            n = stack.pop()
            if not n.get("ignored"):
                yield n
            kids = [self.by_id[c] for c in n.get("childIds", []) if c in self.by_id]
            stack.extend(reversed(kids))

    def children(self, n: AXNode) -> list[AXNode]:
        """Non-ignored children, flattening through ignored intermediaries."""
        out: list[AXNode] = []
        for cid in n.get("childIds", []):
            c = self.by_id.get(cid)
            if c is None:
                continue
            out.extend(self.children(c) if c.get("ignored") else [c])
        return out

    def ancestor(self, n: AXNode, roles: frozenset[str]) -> AXNode | None:
        cur = self.by_id.get(n.get("parentId", ""))
        while cur is not None and role(cur) not in roles:
            cur = self.by_id.get(cur.get("parentId", ""))
        return cur

    def named_parent(self, n: AXNode) -> AXNode | None:
        cur = self.by_id.get(n.get("parentId", ""))
        while cur is not None and cur.get("ignored"):
            cur = self.by_id.get(cur.get("parentId", ""))
        return cur

    # --------------------------------------------------------------- tables

    def is_container(self, n: AXNode) -> bool:
        stack = self.children(n)
        while stack:
            c = stack.pop()
            if role(c) in STRUCTURAL_ROLES:
                return True
            stack.extend(self.children(c))
        return False

    def own_cell(self, n: AXNode) -> AXNode | None:
        return n if role(n) in CELL_ROLES else self.ancestor(n, CELL_ROLES)

    def row_cells(self, row: AXNode) -> list[AXNode]:
        return [c for c in self.children(row) if role(c) in CELL_ROLES]

    def in_data_table(self, n: AXNode) -> bool:
        table = self.ancestor(n, TABLE_ROLES)
        return table is not None and table["nodeId"] in self.headered

    def header_row(self, table: AXNode) -> AXNode | None:
        stack = self.children(table)
        while stack:
            c = stack.pop(0)
            if role(c) in ROW_ROLES and any(role(x) == "columnheader" for x in self.row_cells(c)):
                return c
            stack = self.children(c) + stack
        return None

    def labels(self, n: AXNode) -> list[str]:
        cell = self.own_cell(n)
        row = self.ancestor(cell, ROW_ROLES) if cell is not None else None
        if cell is None or row is None:
            return []
        cells = self.row_cells(row)
        col = next((i for i, c in enumerate(cells) if c["nodeId"] == cell["nodeId"]), None)
        found: list[str] = []
        if self.in_data_table(cell):
            table = self.ancestor(cell, TABLE_ROLES)
            hdr = self.header_row(table) if table is not None else None
            if hdr is not None and col is not None and role(cell) not in HEADER_ROLES:
                hcells = self.row_cells(hdr)
                if col < len(hcells) and role(hcells[col]) == "columnheader":
                    found.append(text(hcells[col]))
            found += [text(c) for c in cells if role(c) == "rowheader" and c is not cell]
        elif col is not None and col > 0:
            left = cells[col - 1]
            if not self.is_container(left):
                found.append(text(left))  # label by adjacency: <td>Member ID</td><td><input>
        return [f for f in found if f]

    # ------------------------------------------------------ classification

    def facts(self, n: AXNode) -> ElementFacts:
        nid = n["nodeId"]
        if nid not in self._facts:
            attrs = self.form_attrs.get(str(n.get("backendDOMNodeId")), {})
            raw_value = (n.get("value") or {}).get("value")
            self._facts[nid] = ElementFacts(
                role=role(n),
                name=text(n),
                value=str(raw_value or "") if role(n) in VALUE_ROLES else None,
                labels=tuple(self.labels(n)),
                input_type=attrs.get("type"),
                autocomplete=attrs.get("autocomplete"),
                in_data_table=self.in_data_table(n),
            )
        return self._facts[nid]

    def classify(self, n: AXNode) -> Classification:
        nid = n["nodeId"]
        if nid not in self._cls:
            self._cls[nid] = self.classifier.classify(self.facts(n))
        return self._cls[nid]

    def anchors(self, n: AXNode) -> tuple[RawText, ...]:
        """Nearby context: a data cell's column header, then the row's other cells."""
        cell = self.own_cell(n)
        row = self.ancestor(cell, ROW_ROLES) if cell is not None else None
        out: list[RawText] = []
        facts = self.facts(n)
        if role(n) in {"cell", "gridcell"} and facts.in_data_table:
            as_header = self.classifier.classify
            out += [
                RawText(label, as_header(ElementFacts("columnheader", label)).name)
                for label in facts.labels
            ]
        if row is not None:
            for sib in self.row_cells(row):
                if cell is not None and sib["nodeId"] == cell["nodeId"]:
                    continue
                if text(sib) and not self.is_container(sib):
                    out.append(RawText(text(sib), self.classify(sib).name))
        return tuple(out[:MAX_ANCHORS])

    # ----------------------------------------------------------- selection

    def keep(self, n: AXNode) -> bool:
        r, t = role(n), text(n)
        if "backendDOMNodeId" not in n:
            return False
        if r in INTERACTIVE_ROLES:
            return True
        if r in CELL_ROLES:
            return bool(t) and not self.is_container(n)
        if r in NAMED_BLOCK_ROLES:
            return bool(t)
        if r == "StaticText":
            parent = self.named_parent(n)
            return bool(t) and (parent is None or text(parent) != t)
        return False

    def perceived(self, n: AXNode, ref: str) -> Perceived:
        c, f = self.classify(n), self.facts(n)
        element = RawElement(
            ref=ref,
            role=f.role,
            name=RawText(f.name, c.name),
            value=None if c.value is None else RawText(f.value or "", c.value),
            enabled=_prop(n, "disabled") is not True,
            frame_path=self.frame.path,
            bbox=None,  # filled by the web surface, which can ask the layout engine
            anchors=self.anchors(n),
        )
        return Perceived(element, self.frame.frame_id, int(n["backendDOMNodeId"]))


def perceive(
    frames: Sequence[FrameAX],
    classifier: SensitivityClassifier,
    form_attrs: Mapping[str, Mapping[str, str]] | None = None,
    *,
    ref_prefix: str = "",
) -> list[Perceived]:
    """Turn per-frame AX trees into classified RawElements with stable, unique refs."""
    out: list[Perceived] = []
    for frame in frames:
        view = _FrameView(frame, classifier, form_attrs or {})
        for n in view.walk():
            if view.keep(n):
                out.append(view.perceived(n, f"{ref_prefix}e{len(out) + 1}"))
    return out
