"""Turning a capability into code a person can read, run and keep.

Two outputs, for two different readers:

* **A regression test** (``pytest``) that replays the capability against its declared cases
  and asserts what each should produce. It uses the engine, so the policy checks, redaction
  and escalation paths all still apply - it is the artifact under test, not a copy of it.
  Put it in CI and a capability that silently stops working fails a build.
* **A page object** (``playwright``) that spells the recorded locators out in ordinary
  Playwright calls: the anchored ladder as ``get_by_role(...).filter(has=...)``, the frame
  path as ``frame_locator`` chains, each checkpoint as an ``expect``. It is for reading and
  debugging - "what does this capability actually click?" - and it carries a header saying
  so, because it has none of the guardrails the engine applies.

Both are generated from the artifact alone, so they cannot drift from it silently: rerun
the generator and the diff is the drift.
"""

from __future__ import annotations

import json
from collections.abc import Sequence
from typing import Any

from waypoint.artifact.schema import Capability, Step
from waypoint.surface.locators import Candidate, LocatorBundle

HEADER = "# Generated by `waypoint codegen` from {id} {version}\n# {note}\n"

TEST_NOTE = ("Re-generate rather than edit: it is the artifact's contract, written as a test. "
             "It drives the real engine, so policy, redaction and escalation still apply.")

PAGE_NOTE = ("For reading and debugging only. Unlike `waypoint replay`, this snippet has no "
             "policy engine, no redaction, no recovery and no escalation, and it covers the "
             "recorded steps alone - preconditions, outcomes and reconciliation belong to the "
             "engine. Never point it at a real system.")


ARIA = {"LayoutTableCell": "cell", "LayoutTable": "table", "LayoutTableRow": "row",
        "StaticText": "paragraph"}
"""Chromium exposes a few non-ARIA roles the engine matches directly; Playwright's
``get_by_role`` takes ARIA roles, so the nearest one is generated instead."""


def _role(role: str | None) -> str:
    return ARIA.get(role or "", role or "generic")


def _literal(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


def _frame_name(frame_path: Sequence[str]) -> str:
    """A readable local name for one recorded frame: ``content``, ``accounts``."""
    if len(frame_path) <= 1:
        return "top"
    last = frame_path[-1]
    if last.startswith("iframe"):
        last = last.split("ifr")[-1].strip("#") or "inner"
    return "".join(c if c.isalnum() else "_" for c in last).strip("_").lower() or "frame"


def _frame_chain(frame_path: Sequence[str]) -> str:
    """The recorded frame path as Playwright frame lookups."""
    chain = "self.page"
    for part in frame_path[1:]:
        if part.startswith("iframe"):
            chain += f".frame_locator({_literal(part)})"
        else:
            chain += f".frame_locator({_literal(f'frame[name={part}]')})"
    return chain


def _frames(cap: Capability) -> dict[tuple[str, ...], str]:
    """Every frame the flow touches, named once so the steps below read as steps."""
    paths: list[tuple[str, ...]] = []
    for _, step in cap.all_steps():
        if step.target is not None:
            paths += [c.frame_path for c in step.target.candidates]
    for spec in cap.outputs.properties.values():
        paths += [c.frame_path for c in spec.extraction.candidates]
    named: dict[tuple[str, ...], str] = {}
    for path in paths:
        if path not in named:
            base = _frame_name(path)
            name, n = base, 2
            while name in named.values():
                name, n = f"{base}_{n}", n + 1
            named[path] = name
    return named


def _candidate_expression(candidate: Candidate, frames: dict[tuple[str, ...], str]) -> str:
    """One candidate as the Playwright call a reader would have written by hand."""
    base = frames.get(tuple(candidate.frame_path)) or _frame_chain(candidate.frame_path)
    role = _role(candidate.role)
    if candidate.kind == "role_name" and candidate.name:
        return f"{base}.get_by_role({_literal(role)}, name={_literal(candidate.name)}, exact=True)"
    if candidate.kind == "label" and candidate.label:
        return f"{base}.get_by_label({_literal(candidate.label)}, exact=True)"
    if candidate.kind == "anchored" and candidate.anchor is not None:
        anchor = candidate.anchor
        text = (f"self.{anchor.text_ref.removeprefix('$inputs.')}"
                if anchor.text_ref else _literal(anchor.text))
        row = (f"{base}.get_by_role('row').filter("
               f"has={base}.get_by_role({_literal(anchor.role)}, name={text}, exact=True))")
        if candidate.column:
            return (f"{row}.get_by_role({_literal(role)}).nth("
                    f"self._column_index({base}, {_literal(candidate.column)}))")
        if candidate.name:
            return (f"{row}.get_by_role({_literal(role)}, "
                    f"name={_literal(candidate.name)}, exact=True)")
        return f"{row}.get_by_role({_literal(role)})"
    if candidate.path:
        return f"{base}.locator({_literal(candidate.path)})"
    return f"{base}.get_by_role({_literal(role)})"


def _locator_lines(bundle: LocatorBundle, frames: dict[tuple[str, ...], str]) -> list[str]:
    lines = []
    for candidate in bundle.candidates:
        note = f"  # tier {candidate.tier} ({candidate.kind})"
        if candidate.is_positional:
            note += " - position plus an identity assertion the engine checks (R-LOC-5)"
        lines.append(f"{_candidate_expression(candidate, frames)}{note}")
    return lines


def _checkpoint_lines(cap: Capability, name: str, frames: dict[tuple[str, ...], str]
                      ) -> list[str]:
    """A checkpoint as assertions - what the engine waits for, spelled out."""
    signature = cap.signatures.get(name)
    if signature is None:
        return [f"# checkpoint: {name}"]
    lines = [f"# checkpoint: {name}"]
    for predicate in _flatten(signature.match):
        element = predicate.element_exists or predicate.element_absent
        if element is not None:
            frame = frames.get(tuple(element.frame)) if element.frame else None
            scope = frame or "self.page"
            role = _role(element.role)
            call = f"{scope}.get_by_role({_literal(role)}"
            if element.name:
                call += f", name={_literal(element.name)}, exact=True"
            elif element.name_ref:
                call += f", name=self.{element.name_ref.removeprefix('$inputs.')}, exact=True"
            elif element.name_contains:
                call += f", name={_literal(element.name_contains)}"
            call += ")"
            state = "to_be_visible()" if predicate.element_exists else "to_have_count(0)"
            lines.append(f"expect({call}.first).{state}")
        elif predicate.text_contains:
            lines.append(f"expect(self.page.get_by_text({_literal(predicate.text_contains)})"
                         ".first).to_be_visible()")
    return lines


def _flatten(predicate: Any) -> list[Any]:
    """The conjunction a checkpoint asserts, as a flat list - ``any``/``none`` stay as is."""
    if predicate.all:
        out: list[Any] = []
        for part in predicate.all:
            out += _flatten(part)
        return out
    return [predicate]


def _step_body(step: Step, frames: dict[tuple[str, ...], str],
               cap: Capability | None = None) -> list[str]:
    lines: list[str] = [f"# {step.intent}"]
    if step.action == "navigate":
        template = (step.url_template or "/").replace("{", "{self.").replace("self.self.", "self.")
        return lines + [f"self.page.goto(self.base_url + f{_literal(template)})"]
    if step.action == "wait_for":
        return lines + ["self.page.wait_for_load_state()"]
    if step.target is None:
        return lines + [f"# (no target recorded for a {step.action} step)"]
    candidates = _locator_lines(step.target, frames)
    lines.append(f"target = {candidates[0]}")
    for extra in candidates[1:]:
        lines.append(f"# fallback: {extra}")
    if step.action == "click":
        lines.append("target.click()")
    elif step.action in ("type", "select"):
        name = (step.value_ref or "").removeprefix("$inputs.").removeprefix("$secrets.")
        source = "self.secrets" if (step.value_ref or "").startswith("$secrets.") else "self"
        value = f"{source}.{name}" if source == "self" else f"{source}[{_literal(name)}]"
        lines.append(f"target.fill({value})" if step.action == "type"
                     else f"target.select_option({value})")
    elif step.action == "key":
        lines.append(f"target.press({_literal(step.key)})")
    elif step.action == "dismiss":
        lines.append("target.click()")
    if cap is not None:
        lines += _checkpoint_lines(cap, step.checkpoint.signature, frames)
    return lines


def page_object(cap: Capability) -> str:
    """A readable Playwright page object: the recorded flow, spelled out."""
    inputs = list(cap.inputs.properties)
    frames = _frames(cap)
    arguments = ", ".join(f"{name}: str" for name in inputs)
    body: list[str] = [
        HEADER.format(id=cap.capability_id, version=cap.version, note=PAGE_NOTE),
        '"""' + cap.description + '"""',
        "",
        "from playwright.sync_api import Page, expect",
        "",
        "",
        f"class {_class_name(cap.capability_id)}:",
        f'    """{cap.name}."""',
        "",
        f"    def __init__(self, page: Page, base_url: str, secrets: dict[str, str], "
        f"{arguments}) -> None:",
        "        self.page = page",
        "        self.base_url = base_url.rstrip('/')",
        "        self.secrets = secrets",
    ]
    body += [f"        self.{name} = {name}" for name in inputs]
    for precondition in cap.preconditions:
        if precondition.remedy is None:
            continue
        method = _method_name(precondition.signature)
        body += [
            "",
            f"    def {method}(self) -> None:",
            f'        """Establish {precondition.signature}: the engine runs this only when '
            f'the state it is written for is recognised (R-OUT-3)."""',
        ]
        body.append("        # The frames this remedy touches.")
        for path, name in frames.items():
            body.append(f"        {name} = {_frame_chain(path)}")
        body.append("")
        for step in precondition.remedy.steps:
            body += [f"        {line}" for line in _step_body(step, frames, cap)]
            body.append("")
    body += [
        "",
        "    @staticmethod",
        "    def _column_index(scope, header: str) -> int:",
        '        """Which column a header sits in - the engine resolves this the same way."""',
        "        headers = scope.get_by_role('columnheader').all_text_contents()",
        "        return headers.index(header)",
        "",
        "    def run(self) -> dict[str, str]:",
    ]
    for precondition in cap.preconditions:
        if precondition.remedy is not None:
            body.append(f"        self.{_method_name(precondition.signature)}()")
    body.append("        # The frames this console nests its screens in.")
    for path, name in frames.items():
        body.append(f"        {name} = {_frame_chain(path)}")
    body.append("")
    for where, step in [(f"steps[{i}]", s) for i, s in enumerate(cap.steps)]:
        body.append(f"        # --- {where}")
        body += [f"        {line}" for line in _step_body(step, frames, cap)]
        body.append("")
    body.append("        return {")
    for name, spec in cap.outputs.properties.items():
        expression = _candidate_expression(spec.extraction.candidates[0], frames)
        body.append(f"            {_literal(name)}: {expression}.inner_text().strip(),")
    body.append("        }")
    body.append("")
    return "\n".join(body)


def regression_test(cap: Capability, cases_path: str = "") -> str:
    """A pytest module that replays the capability against its declared cases."""
    cases = cases_path or f"capabilities/{cap.capability_id}/cases.yaml"
    outcomes = ", ".join(o.name for o in cap.outcomes) or "none declared"
    return f'''{HEADER.format(id=cap.capability_id, version=cap.version, note=TEST_NOTE)}
"""Replays {cap.capability_id} {cap.version} against its declared cases.

Outputs: {", ".join(cap.outputs.properties) or "none"}. Business outcomes: {outcomes}.
Each case says what it must produce, so a run that succeeds where an outcome was due fails
here too. Point BASE_URL at a fixture, never at a real system.
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest

from waypoint.artifact.schema import load
from waypoint.policy.secrets import SecretBroker
from waypoint.replay.engine import ReplayOptions, replay
from waypoint.replay.stability import case_injector, load_cases

ARTIFACT = Path({_literal(f"capabilities/{cap.capability_id}/{cap.version}.json")})
CASES = Path({_literal(cases)})
BASE_URL = os.environ.get("WAYPOINT_BASE_URL", "http://127.0.0.1:8080")


@pytest.fixture(scope="module")
def capability():
    return load(ARTIFACT)


@pytest.mark.parametrize("case", load_cases(CASES), ids=lambda c: c.label)
def test_case(capability, case, tmp_path):
    options = ReplayOptions(
        base_url=BASE_URL,
        evidence_root=tmp_path,
        secrets=SecretBroker(),
        capture_steps=False,
        state_db=tmp_path / "state.db",
        ledger_db=tmp_path / "state.db",
        require_confidence=False,  # This is a measurement; approval and policy still apply.
        injected=case.inject,
        after_preconditions=case_injector(case),
    )
    result = replay(capability, dict(case.inputs), options)
    if case.expect_status:
        assert result.status == case.expect_status, result.failure
    if case.expect_outcome:
        assert result.outcome == case.expect_outcome
    if result.status == "success":
        assert set(result.outputs or {{}}) == set(capability.outputs.properties)
'''


def _method_name(signature: str) -> str:
    return "establish_" + "".join(c if c.isalnum() else "_" for c in signature).strip("_").lower()


def _class_name(capability_id: str) -> str:
    return "".join(part.title() for part in capability_id.split("_")) + "Page"


def generate(cap: Capability, target: str, **kwargs: Any) -> str:
    if target == "pytest":
        return regression_test(cap, **kwargs)
    if target == "playwright":
        return page_object(cap)
    raise ValueError(f"unknown target {target!r}: use 'pytest' or 'playwright'")
